package com.aicontrolplane.gateway.middleware;

public final class GatewayHeaders {

    // Propagated inbound or generated by RequestIdFilter.
    public static final String REQUEST_ID = "X-Request-ID";

    // Identifies the calling application.
    // v0.2: caller supplies this header explicitly; AuthFilter attaches it to request context.
    // v0.5: derived from application identity in the token; this header is no longer trusted.
    public static final String APPLICATION_ID = "X-Application-Id";

    private GatewayHeaders() {}
}
